kind: pipeline
name: openex-tests

steps:
- name: api-tests
  image:  maven:3.8.4-openjdk-17
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/openex
    SPRING_DATASOURCE_USERNAME: openex
    SPRING_DATASOURCE_PASSWORD: openex
    MINIO_ENDPOINT: minio
    MINIO_PORT: 9000
    MINIO_ACCESS-KEY: minioadmin
    MINIO_ACCESS-SECRET: minioadmin
  commands:
  - cd openex-api
  - mvn test

- name: frontend-tests
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  commands: 
  - cd openex-front
  - yarn install
  - yarn build
  - yarn test

- name: build-circleci
  image: curlimages/curl
  commands:
  - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: build-circleci-release
  image: curlimages/curl
  commands:
  - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    event:
      - tag

services:
- name: pgsql
  image: postgres:13-alpine
  environment:
    POSTGRES_USER: openex
    POSTGRES_PASSWORD: openex
    POSTGRES_DB: openex
- name: minio
  image: minio/minio:RELEASE.2021-11-09T03-21-45Z
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  command: [ server, /data ]
