kind: pipeline
type: docker
name: openex-tests-pull-request
concurrency: {
  limit: 2
}

trigger:
  event:
    - pull_request

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: api-tests
    image: maven:3.8.7-openjdk-18
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS-KEY: minioadmin
      MINIO_ACCESS-SECRET: minioadmin
    commands:
      - mvn install
    depends_on:
      - submodules

  - name: frontend-tests
    image: node:20.10.0-alpine3.18
    commands:
      - cd openex-front
      - yarn install
      - yarn build
      - yarn check-ts
      - yarn lint
      - yarn i18n-checker
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

services:
  - name: minio
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]

---
kind: pipeline
name: openex-tests-master

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: api-tests
    image: maven:3.8.7-openjdk-18
    environment:
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS-KEY: minioadmin
      MINIO_ACCESS-SECRET: minioadmin
    commands:
      - mvn install

  - name: frontend-tests
    image: node:20.10.0-alpine3.18
    commands:
      - cd openex-front
      - yarn install
      - yarn build
      - yarn check-ts
      - yarn lint
      - yarn i18n-checker
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

  - name: codecov
    image: robertstettner/drone-codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files: openex-api/target/site/jacoco/jacoco.xml

  - name: build-circleci
    image: curlimages/curl
    commands:
      - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        exclude:
          - tag

  - name: build-circleci-release
    image: curlimages/curl
    commands:
      - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        - tag

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: drone
      channel: notifications
    when:
      status: [ success, failure ]

services:
  - name: minio
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]
