kind: pipeline
name: openex-tests

steps:
- name: init-service
  image: postgres:13-alpine
  commands:
  - sleep 30
  - PGPASSWORD=openex psql --host=pgsql --port=5432 --username=openex --dbname=openex -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'

- name: api-tests
  image:  maven:3.8.4-openjdk-17
  commands:
  - cd openex-api
  - mvn install -DskipTests

- name: frontend-tests
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  commands: 
  - cd openex-front
  - yarn install
  - yarn build
  - yarn test

- name: build-circleci
  image: curlimages/curl
  commands:
  - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: build-circleci-release
  image: curlimages/curl
  commands:
  - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenEx-Platform/openex/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    event:
      - tag

services:
- name: pgsql
  image: postgres:13-alpine
  environment:
    POSTGRES_USER: openex
    POSTGRES_PASSWORD: openex
    POSTGRES_DB: openex