version: 2.1
orbs:
  slack: circleci/slack@4.13.1
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build_frontend:
    working_directory: ~/openbas
    docker:
      - image: nikolaik/python-nodejs:python3.10-nodejs20
    resource_class: large
    steps:
      - run:
          command: apt-get update --allow-insecure-repositories --allow-unauthenticated && apt-get install -y build-essential libffi-dev curl
      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init --recursive --jobs 8
      - run:
          working_directory: ~/openbas/openbas-front
          command: yarn install
      - run:
          working_directory: ~/openbas/openbas-front
          command: NODE_OPTIONS=--max-old-space-size=8096 yarn build
          no_output_timeout: 30m
      - run:
          working_directory: ~/
          command: cp -a openbas openbas_docker && cp -a openbas openbas_musl
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openbas
            - openbas_docker
            - openbas_musl

  build_platform:
    working_directory: ~/openbas
    docker:
      - image: maven:3.9.6-eclipse-temurin-21
    steps:
      - attach_workspace:
          at: ~/
      - run:
          working_directory: ~/openbas
          command: mvn install -DskipTests -Pdev
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openbas

  build_platform_musl:
    working_directory: ~/openbas_musl
    docker:
      - image: maven:3.9.6-eclipse-temurin-21-alpine
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - run:
          working_directory: ~/openbas_musl
          command: mvn install -DskipTests -Pdev
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openbas_musl

  package_rolling:
    working_directory: ~/openbas
    docker:
      - image: maven:3.9.6-eclipse-temurin-21
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir -p release/openbas
      - run: cp -a ./openbas-api/target/openbas-api.jar release/openbas/ && cp -a ./openbas-api/src/main/resources/application.properties release/openbas/
      - run:
          working_directory: ~/openbas/release
          command: tar -zcvf "openbas-$(date '+%Y%m%d').tar.gz" openbas
      - run:
          working_directory: ~/openbas/release
          command: curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T openbas-$(date '+%Y%m%d').tar.gz "https://filigran.jfrog.io/artifactory/openbas/openbas-$(date '+%Y%m%d').tar.gz"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  package_rolling_musl:
    working_directory: ~/openbas_musl
    docker:
      - image: maven:3.9.6-eclipse-temurin-21
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir -p release/openbas
      - run: cp -a ./openbas-api/target/openbas-api.jar release/openbas/ && cp -a ./openbas-api/src/main/resources/application.properties release/openbas/
      - run:
          working_directory: ~/openbas_musl/release
          command: tar -zcvf "openbas-$(date '+%Y%m%d')_musl.tar.gz" openbas
      - run:
          working_directory: ~/openbas_musl/release
          command: curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T openbas-$(date '+%Y%m%d')_musl.tar.gz "https://filigran.jfrog.io/artifactory/openbas/openbas-$(date '+%Y%m%d')_musl.tar.gz"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  deploy_testing:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: kubectl --server=https://api.staging.eu-west.filigran.io --token=$K8S_TOKEN -n customer-testing rollout restart deployment

  docker_build_platform:
    working_directory: ~/openbas_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name mybuilder --use
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image openbas/platform
          command: docker buildx build --platform $BUILDX_PLATFORMS -f Dockerfile_circleci -t openbas/platform:latest -t openbas/platform:${CIRCLE_TAG} --push .
          no_output_timeout: 30m
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  docker_build_platform_rolling:
    working_directory: ~/openbas_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name multiarch --driver docker-container --use
            docker buildx inspect --bootstrap
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          working_directory: ~/openbas_docker
          name: Build Docker image openbas/platform
          command: docker buildx build --platform $BUILDX_PLATFORMS -f Dockerfile_circleci -t openbas/platform:rolling --push .
          no_output_timeout: 30
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  notify_rolling:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: sudo apt-get update -qq && sudo apt install curl
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: sudo apt-get update -qq && sudo apt install curl
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL

workflows:
  openbas:
    jobs:
      - build_frontend:
          filters:
            tags:
              only: /.*/
      - build_platform:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
      - build_platform_musl:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
      - package_rolling:
          requires:
            - build_platform
          filters:
            branches:
              only:
                - master
      - package_rolling_musl:
          requires:
            - build_platform_musl
          filters:
            branches:
              only:
                - master
      - docker_build_platform_rolling:
          requires:
            - build_frontend
          filters:
            branches:
              only:
                - master
      - docker_build_platform:
          requires:
            - build_frontend
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy_testing:
          requires:
            - docker_build_platform_rolling
      - notify_rolling:
          requires:
            - deploy_testing
            - package_rolling
            - package_rolling_musl
      - notify:
          requires:
            - docker_build_platform
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/
